import type { Metadata } from "next";
import "./globals.css";
import { Title } from "@front/components/sidebar";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className="antialiased">
        <div className="h-full w-full">
          <Title />
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
