import type { Metadata } from "next";
import "./globals.css";
import { Title } from "@frontend/components/sidebar";
import Provider from "@frontend/providers";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className="antialiased">
        <Provider>
          <div className="h-full w-full">
            <Title />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
